import type { QuestionConfig } from '@/types'

/**
 * Въпросник — кратък, ясен, mobile-first.
 * Задължителни: профил, цели, активност, сън, хидратация.
 * Останалото е по избор (може да се пропусне).
 */
export const defaultQuestions: QuestionConfig[] = [
  {
    id: 'name',
    type: 'text',
    question: 'Как се казвате?',
    required: true,
    validation: { min: 2 },
  },
  {
    id: 'age',
    type: 'number',
    question: 'На колко години сте?',
    required: true,
    validation: { min: 1, max: 120 },
  },
  {
    id: 'gender',
    type: 'radio',
    question: 'Пол',
    required: true,
    options: [
      { value: 'male', label: 'Мъж' },
      { value: 'female', label: 'Жена' },
      { value: 'other', label: 'Предпочитам да не казвам' },
    ],
  },
  {
    id: 'weight',
    type: 'number',
    question: 'Тегло (кг)',
    required: true,
    validation: { min: 20, max: 300 },
  },
  {
    id: 'height',
    type: 'number',
    question: 'Ръст (см)',
    required: true,
    validation: { min: 50, max: 250 },
  },
  {
    id: 'goals',
    type: 'checkbox',
    question: 'Какво искате да постигнете?',
    description: 'Можете да изберете няколко',
    required: true,
    allowOther: true,
    options: [
      { value: 'Отслабване', label: 'Отслабване' },
      { value: 'Подобряване на здравето', label: 'По-добро здраве' },
      { value: 'Увеличаване на енергията', label: 'Повече енергия' },
      { value: 'Подобряване на съня', label: 'По-добър сън' },
      { value: 'Емоционален баланс', label: 'Емоционален баланс' },
      { value: 'Укрепване на мускулите', label: 'По-силни мускули' },
      { value: 'Антиейджинг', label: 'Антиейджинг' },
    ],
  },
  {
    id: 'healthStatus',
    type: 'checkbox',
    question: 'Имате ли някое от следните състояния?',
    description: 'По избор — помага за по-безопасен план',
    required: false,
    allowOther: true,
    options: [
      { value: 'Затлъстяване', label: 'Затлъстяване' },
      { value: 'Инсулинова резистентност', label: 'Инсулинова резистентност' },
      { value: 'Диабет 2 тип', label: 'Диабет тип 2' },
      { value: 'Автоимунен тиреоидит', label: 'Автоимунен тиреоидит' },
      { value: 'Рефлуксна болест', label: 'Рефлукс' },
      { value: 'Хипертония', label: 'Високо кръвно' },
      { value: 'Менопауза', label: 'Менопауза' },
      { value: 'Бременност', label: 'Бременност' },
    ],
  },
  {
    id: 'complaints',
    type: 'textarea',
    question: 'Какво ви притеснява в момента?',
    description: 'Симптоми, оплаквания — по избор',
    required: false,
  },
  {
    id: 'medicalConditions',
    type: 'textarea',
    question: 'Хронични заболявания или лечение',
    description: 'Включете и семейна обремененост, ако е важно',
    required: false,
  },
  {
    id: 'activityLevel',
    type: 'radio',
    question: 'Колко често се движите?',
    required: true,
    options: [
      { value: 'sedentary', label: 'Почти не се движа' },
      { value: 'light', label: '1–2 пъти седмично' },
      { value: 'moderate', label: '3–4 пъти седмично' },
      { value: 'active', label: '5–6 пъти седмично' },
      { value: 'very-active', label: 'Всеки ден, интензивно' },
    ],
  },
  {
    id: 'stressLevel',
    type: 'radio',
    question: 'Колко стрес имате ежедневно?',
    required: true,
    options: [
      { value: 'low', label: 'Малко' },
      { value: 'moderate', label: 'Умерено' },
      { value: 'high', label: 'Много' },
      { value: 'very-high', label: 'Постоянно висок' },
    ],
  },
  {
    id: 'sleepHours',
    type: 'slider',
    question: 'Колко часа спите?',
    required: true,
    validation: { min: 3, max: 12 },
  },
  {
    id: 'sleepQuality',
    type: 'radio',
    question: 'Как оценявате съня си?',
    required: true,
    options: [
      { value: 'poor', label: 'Лош' },
      { value: 'fair', label: 'Среден' },
      { value: 'good', label: 'Добър' },
      { value: 'excellent', label: 'Отличен' },
    ],
  },
  {
    id: 'hydration',
    type: 'slider',
    question: 'Колко чаши вода пиете на ден?',
    description: 'Една чаша ≈ 250 ml',
    required: true,
    validation: { min: 0, max: 15 },
  },
  {
    id: 'dietaryProfile',
    type: 'checkbox',
    question: 'Храните се по някакъв режим?',
    required: false,
    allowOther: true,
    options: [
      { value: 'Вегетариански', label: 'Вегетариански' },
      { value: 'Веган', label: 'Веган' },
      { value: 'Интермитентен фастинг', label: 'Интермитентен глад' },
      { value: 'Кето', label: 'Кето' },
      { value: 'Средиземноморска', label: 'Средиземноморска' },
      { value: 'Безглутенова', label: 'Без глутен' },
    ],
  },
  {
    id: 'dietaryHabits',
    type: 'checkbox',
    question: 'Кои от тези навици имате?',
    required: false,
    options: [
      { value: 'Бърза храна', label: 'Често бърза храна' },
      { value: 'Сладки храни', label: 'Много сладко' },
      { value: 'Алкохол', label: 'Редовен алкохол' },
      { value: 'Нередовност', label: 'Нередовно хранене' },
      { value: 'Прескачане на закуска', label: 'Прескачам закуска' },
      { value: 'Късно хранене', label: 'Храня се късно вечер' },
    ],
  },
  {
    id: 'foodRestrictions',
    type: 'textarea',
    question: 'Алергии или непоносимост към храни',
    description: 'Например: лактоза, глутен, ядки',
    required: false,
  },
  {
    id: 'medications',
    type: 'textarea',
    question: 'Лекарства и добавки',
    description: 'Включете витамини и безрецептурни продукти',
    required: false,
  },
  {
    id: 'documents',
    type: 'file',
    question: 'Медицински документи',
    description: 'По избор — лабораторни резултати, снимки',
    required: false,
  },
]
